### ISSUE TITLE
After clicking a route link and then navigating back, top-routes gets all screwey

### ISSUE THREAD

**Issue by skeltont** [protoscend/protoscend#154]
we need to replace this fking plugin for real...

![screen shot 2016-08-04 at 9 53 45 am](https://cloud.githubusercontent.com/assets/4512337/17410668/8e05d01c-5a29-11e6-8ac7-4a9f906ea7d3.png)

**Comment by jonahgeorge** [comment]
Wtf turbolinks

**Comment by jonahgeorge** [comment]
If we are going to keep Turbolinks around, we should probably just install this:
https://github.com/kossnocorp/jquery.turbolinks
