### ISSUE TITLE
Naming of organization and repo

### ISSUE THREAD

**Issue by skeltont** [protoscend/protoscend#17]
Now that we have a cool logo for this team we should really have a better name. Not assigning this to anyone because we should all think about it. Over time try to comment some ideas.

**Comment by jonahgeorge** [comment]
<img width="435" alt="screen shot 2015-11-14 at 7 45 38 pm" src="https://cloud.githubusercontent.com/assets/2058205/11167085/4baa4fae-8b08-11e5-8d38-d2558a653576.png">

This is critical.

**Comment by jonahgeorge** [comment]
#### Generic
- routes
- routes-management

#### Locations
- Monkeyface

#### Misc
- [Comici](https://en.wikipedia.org/wiki/Emilio_Comici)
- [Diamox](https://en.wikipedia.org/wiki/Acetazolamide)
- Cairn
- Skyhook
- Talus
- Testpiece

#### Knots
- Klemheist
- Distel
- Prusik
- Munter

**Comment by jonahgeorge** [comment]
- Munter
- Skyhook
- Talus
- Testpiece
- Monkeyface

**Comment by jonahgeorge** [comment]
Rockwell

**Comment by skeltont** [comment]
bc i can make ur bed rock

**Comment by jonahgeorge** [comment]
:wink:

**Comment by jonahgeorge** [comment]
From Slack:
- verderock
- verdewall
- cruxfactory
- cruxproject
- routetraq
- rockproject
- reclimb
- ascentkit
- cruxcatalog
- rockwallref
- setterschoice
- settersguide
- mesaverde
- routecloud
- routebrowse
- routeapp
- routecatalog
- rockportal
- Everyday Climb
- Rock Toolbox
- FiveStar Climbing
- Rock Engineering
- Climb Anytime
- {Rock | Climb} Passport
- {Climbing | Rock Gym} Passort
- Climb Blueprint
- Simple Climbing
- Climbing Labs

**Comment by jonahgeorge** [comment]
- Route Pilot
- Route Lead
- Route Monitor
- Route Manager

**Comment by skeltont** [comment]
my votes are for: 
- verderock
- routetraq

**Comment by jonahgeorge** [comment]
rutaverde -> "Green Route"

**Comment by jonahgeorge** [comment]
👏

**Comment by skeltont** [comment]
we did it!
