### ISSUE TITLE
Fix pagination on 'View Profiles'

### ISSUE THREAD

**Issue by skeltont** [protoscend/protoscend#2]
When a user filters down the results in anyway the pagination needs to reflect the new total number of listings. Currently, if there are 15 records available and they filter down to 5 then the pagination SHOULD show page 1 only, not 1 through 3.

**Comment by jonahgeorge** [comment]
I'll tackle this.

Options:
1. Server-side magic via multiple queries
2. Return _all_ of the users matching the filter params and let React do the pagination

Definitely leaning towards 2 but let me know what you think
