### ISSUE TITLE
Fix denied routing. 

### ISSUE THREAD

**Issue by skeltont** [protoscend/protoscend#3]
Right now, if a user tries to view a page on the client side (the api won't return data because of no auth-token) the page renders for a moment then redirects to the home page.

This isn't a security flaw or anything, because they can't interact with the api, but it's very ugly and needs to be reworked. Currently jquery is just checking for local session variables and then if they don't exist it does a redirect. This is gross and needs to be implemented in a less hacky way.

**Comment by skeltont** [comment]
This will probably soon be handled by us committing to server-rendered views with occasional bits of react.

**Comment by jonahgeorge** [comment]
I can work on this when we meet up Saturday

**Comment by skeltont** [comment]
Closing because we moved away from creating a pure API with this.
