### ISSUE TITLE
Incorrect Title on User index page

### ISSUE THREAD

**Issue by MillerJL** [protoscend/protoscend#31]
/app/views/user/index.html.erb

```
<header>
  <h1 style="display:inline-block;">Routes</h1>
```

View users page title says "Routes" instead of "Users". Completely unacceptable.

**Comment by skeltont** [comment]
![image](https://cloud.githubusercontent.com/assets/4512337/11290546/a9c46736-8eec-11e5-984f-ce0617ffeee0.png)

**Comment by jonahgeorge** [comment]
:ugh:

**Comment by skeltont** [comment]
:fire:

**Comment by MillerJL** [comment]
:clap:

**Comment by MillerJL** [comment]
:open_hands: :clap: :raised_hands:

**Comment by skeltont** [comment]
@MillerJL THE TIME HAS COME
