### ISSUE TITLE
Image handling for individual routes

### ISSUE THREAD

**Issue by skeltont** [protoscend/protoscend#36]
<img width="920" alt="screen shot 2016-01-09 at 1 25 02 pm" src="https://cloud.githubusercontent.com/assets/4512337/12218458/835d5ade-b6d4-11e5-9d2f-4b8788332c9b.png">

**Comment by MillerJL** [comment]
![](https://cloud.githubusercontent.com/assets/4512337/11290546/a9c46736-8eec-11e5-984f-ce0617ffeee0.png)

**Comment by jonahgeorge** [comment]
Oh, I meant storing images of individual routes. 
Using something like this[1] with a defined `Image` model. Then we can have as many images per route as we want and don't have to do only weird stuff to upload to S3 or wherever.

[1] https://github.com/refile/refile
