### ISSUE TITLE
Format user serializer to return specific data when viewing

### ISSUE THREAD

**Issue by skeltont** [protoscend/protoscend#4]
When a user views a profile and the return object comes back, it will return the auth token of that user. We don't want that, so we should find a way to remove the auth token from being viewable. 

This also goes for the 'view' page that lists all the user.

**Comment by jonahgeorge** [comment]
Two Options (of many):
1. Entirely remove the `auth_token` from the `UserSerializer` and then customize the JSON coming back from the `Api::AuthenticationController`
2. Override the `filter` method for the `UserSerializer`, deleting the `auth_token` attribute when the current user is not the owner of the object. 

https://github.com/rails-api/active_model_serializers/tree/0-9-2#attributes
