### ISSUE TITLE
User Interface

### ISSUE THREAD

**Issue by jonahgeorge** [protoscend/protoscend#47]
#### Create
- [x] Registering
#### Show
- Who can view info (policies)?
#### Edit
- [x] Password changing
- [x] Password reset (due to data migration for alpha)
#### Destroy
- [ ] soft deletes

**Comment by jonahgeorge** [comment]
Status? @skeltont

**Comment by skeltont** [comment]
no ability to permanently or soft-delete users yet. was waiting for a discussion on this later.
