### ISSUE TITLE
Route Interface

### ISSUE THREAD

**Issue by jonahgeorge** [protoscend/protoscend#48]
#### Index
- [x] Search box should downcase search term
#### Show
- [x] Images #36
- [x] Comments
- [x] General information
#### Edit
- [x] Review Policies 
  - All should be edit-able by anyone above `supervisor`
  - "Owned" should be edit-able by `staff`
#### Destroy
- Soft delete

**Comment by skeltont** [comment]
the search box for routes does lower case, not users :|
