### ISSUE TITLE
Report Interface

### ISSUE THREAD

**Issue by jonahgeorge** [protoscend/protoscend#49]
#### Maintenance
- List of maintenance tickets
- Sort by priority and date created
- Consider metrics
#### Expiring Routes
- Routes that have expired
- Routes that are expiring soon
- Consider metrics

**Comment by skeltont** [comment]
this issue is complete when john creates the expiring routes page.

**Comment by jonahgeorge** [comment]
Expiring Routes is complete. Can we close this?

**Comment by skeltont** [comment]
I'll close it, because we met these reqs. I still am open to (and expect to) add more reports in the future.
