### ISSUE TITLE
Public Interface

### ISSUE THREAD

**Issue by jonahgeorge** [protoscend/protoscend#50]
- Per gym/account
- New Routes
- Announcements
- Events?

**Comment by skeltont** [comment]
This shit is not built for public users at the moment.

**Comment by skeltont** [comment]
should we have an anonymous user that is automatically set when no one is logged in?

**Comment by MillerJL** [comment]
This could work. It could also give us an easy way to have all anonymous content tied to one location.

**Comment by jonahgeorge** [comment]
Maybe you have to be a logged in user to set that application to anonymous?

This would allow gym staff to log in (with their account) and then set the session to anonymous for "Kiosk mode". That might actually be a better term for this-- rather than an "anonymous user" its the "kiosk user".
